# Generated by Django 2.2.1 on 2019-05-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190528_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='context',
            new_name='content',
        ),
    ]
